Menu auto shortcut hints where possible
roadrunner1776/magik pull request #20
Opened 2021-09-01 13:55 UTC by ReinhardHahn

_**Note that this pull request includes all changes of Pull-Request #19 as well**_

In addition to #19 in all menu entry definitions the `:keys`-entry has been removed, where ever the there is only one shortcut which is displayed automatically without specification in the menu entry definition.

This has the advantage for users, which change the key bindings e.g. in their `.emacs` - file, the short-cut hints in the menu are displayed correctly

2023-01-16 15:50 UTC, roadrunner1776 requested changes
Look good; can you rebase this on current master?

2023-04-28 23:29 UTC, ReinhardHahn commented
I've rebased the branch.
If you merge the last commit, also the changes of PR #70 will be included, so there will be no need to merge PR #70 anymore

2023-05-03 13:34 UTC, roadrunner1776 approved these changes

2023-05-03 13:37 UTC, roadrunner1776 requested changes
This pull request still has open conflicts and therefor cannot be merged

2023-05-07 17:16 UTC, merged